backend:
  name: git-gateway
  branch: master
media_folder: static/images
public_folder: /images
publish_mode: editorial_workflow
collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - {
          label: "Show in homepage",
          name: "show_in_homepage",
          widget: "boolean",
          default: true,
        }
      - {
          label: "Show description",
          name: "show_description",
          widget: "boolean",
          default: true,
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "select",
          multiple: true,
          options:
            [
              "Tech",
              "Automation",
              "Git",
              "Server",
              "BIT",
              "IFTTT",
              "iPad",
              "RSS",
              "Shortcuts",
              "Twitter",
              "Weibo",
            ],
        }
      - {
          label: "Categories",
          name: "categories",
          widget: "select",
          options:
            ["技术", "Automation", "服务器能拿来干什么", "用 iPad 学习的一天"],
        }
      - { label: "Featured Image", name: "featured_image", widget: "string" }
      - { label: "Comment", name: "comment", widget: "boolean", default: true }
      - { label: "TOC", name: "toc", widget: "boolean", default: true }
      - {
          label: "Auto collapse TOC",
          name: "autoCollapseToc",
          widget: "boolean",
          default: true,
        }
      - { label: "Body", name: "body", widget: "markdown" }
